[build]
  publish = "."
    command = ""
      ignore = "exit 0"

      [functions]
        directory = "/dev/null"

        [[headers]]
          for = "/*"
            [headers.values]
                Cache-Control = "public, max-age=0, must-revalidate"

                [[redirects]]
                  from = "/*"
                    to = "https://fairchancefinder.base44.app/:splat"
                      status = 301
                        force = true
