var JOBS = [
  {
    id: 1,
    title: "Warehouse Associate",
    company: "Amazon",
    location: "Phoenix, AZ",
    category: "warehouse",
    type: "Full-time",
    pay: "$17–20/hr",
    description: "Pick, pack, and ship orders in a fast-paced fulfillment center. Physical role requiring lifting up to 50 lbs. Multiple shifts available including nights and weekends.",
    requirements: ["Must be able to lift 50 lbs", "Standing/walking for 10+ hours", "No experience required", "Must be 18+"],
    fairChance: true,
    fairChanceNote: "Amazon considers qualified applicants with criminal histories consistent with applicable law.",
    applyUrl: "https://www.amazon.jobs/en/locations/phoenix"
  },
  {
    id: 2,
    title: "Package Handler",
    company: "UPS",
    location: "Tempe, AZ",
    category: "warehouse",
    type: "Part-time / Full-time",
    pay: "$16–19/hr",
    description: "Load and unload packages in a warehouse environment. Fast-paced work with opportunities for advancement to driver and supervisor roles.",
    requirements: ["Must be able to lift up to 70 lbs", "No experience necessary", "Must be 18+", "Flexible scheduling"],
    fairChance: true,
    fairChanceNote: "UPS is an equal opportunity employer that considers all qualified applicants regardless of criminal history.",
    applyUrl: "https://www.jobs-ups.com/"
  },
  {
    id: 3,
    title: "Delivery Driver",
    company: "FedEx Ground",
    location: "Tempe, AZ",
    category: "driving",
    type: "Full-time",
    pay: "$18–22/hr",
    description: "Deliver packages along a set route in the Tempe and East Valley area. Company vehicle provided. Great for people who enjoy working independently.",
    requirements: ["Valid driver's license", "Clean driving record (past 3 years)", "Must pass DOT physical", "Ability to lift 75 lbs"],
    fairChance: true,
    fairChanceNote: "FedEx Ground considers applicants with criminal records on a case-by-case basis.",
    applyUrl: "https://careers.fedex.com/ground"
  },
  {
    id: 4,
    title: "CDL Truck Driver",
    company: "Schneider",
    location: "Phoenix, AZ",
    category: "driving",
    type: "Full-time",
    pay: "$22–28/hr",
    description: "Regional and OTR driving positions. Consistent routes with home time. Schneider provides paid CDL training for qualified candidates.",
    requirements: ["CDL-A license (or willingness to train)", "Must be 21+", "Ability to pass DOT physical and drug screen"],
    fairChance: true,
    fairChanceNote: "Schneider is a fair-chance employer and reviews each applicant individually.",
    applyUrl: "https://schneiderjobs.com/"
  },
  {
    id: 5,
    title: "Line Cook",
    company: "Buffalo Wild Wings",
    location: "Mesa, AZ",
    category: "food",
    type: "Full-time",
    pay: "$15–18/hr",
    description: "Prepare food items according to recipes and quality standards. Work in a fast-paced kitchen environment with a team-oriented crew.",
    requirements: ["No experience required (training provided)", "Ability to stand for extended periods", "Food handler's card (can obtain after hire)", "Must be 18+"],
    fairChance: true,
    fairChanceNote: "Buffalo Wild Wings and Inspire Brands practice fair-chance hiring across locations.",
    applyUrl: "https://careers.buffalowildwings.com/"
  },
  {
    id: 6,
    title: "Kitchen Team Member",
    company: "Chipotle",
    location: "Chandler, AZ",
    category: "food",
    type: "Full-time / Part-time",
    pay: "$14–17/hr",
    description: "Join the Chipotle crew preparing fresh food, working the line, and maintaining a clean restaurant. Advancement opportunities to management.",
    requirements: ["No experience needed", "Must be 16+ (18+ for some roles)", "Ability to work in a fast-paced environment"],
    fairChance: true,
    fairChanceNote: "Chipotle has committed to fair-chance hiring and does not ask about criminal history on initial applications.",
    applyUrl: "https://jobs.chipotle.com/"
  },
  {
    id: 7,
    title: "Construction Laborer",
    company: "Turner Construction",
    location: "Phoenix, AZ",
    category: "construction",
    type: "Full-time",
    pay: "$18–24/hr",
    description: "Support construction projects by preparing sites, loading materials, operating equipment, and assisting skilled tradespeople. Learn on the job.",
    requirements: ["No formal experience required", "Must be physically fit", "Willing to work outdoors in heat", "OSHA 10 certification preferred"],
    fairChance: true,
    fairChanceNote: "Turner Construction partners with reentry programs and actively recruits fair-chance workers.",
    applyUrl: "https://www.turnerconstruction.com/careers"
  },
  {
    id: 8,
    title: "Concrete Finisher",
    company: "Sundt Construction",
    location: "Scottsdale, AZ",
    category: "construction",
    type: "Full-time",
    pay: "$20–26/hr",
    description: "Pour, smooth, and finish concrete surfaces for commercial and residential projects. Work with experienced crews on high-profile Arizona developments.",
    requirements: ["1+ year concrete experience preferred", "Must be physically fit", "Valid driver's license helpful", "Willing to work early mornings"],
    fairChance: true,
    fairChanceNote: "Sundt Construction evaluates candidates holistically and participates in second-chance hiring programs.",
    applyUrl: "https://www.sundt.com/careers"
  },
  {
    id: 9,
    title: "HVAC Technician Apprentice",
    company: "Parker & Sons",
    location: "Phoenix, AZ",
    category: "trades",
    type: "Full-time",
    pay: "$16–22/hr",
    description: "Learn HVAC installation and repair under experienced technicians. Paid apprenticeship with path to certification and higher pay.",
    requirements: ["No HVAC experience needed", "Mechanical aptitude", "Valid driver's license", "Willingness to learn and work in heat"],
    fairChance: true,
    fairChanceNote: "Parker & Sons considers all qualified applicants including those with criminal backgrounds.",
    applyUrl: "https://www.parkerandsons.com/careers"
  },
  {
    id: 10,
    title: "Electrician Helper",
    company: "Rosendin Electric",
    location: "Tempe, AZ",
    category: "trades",
    type: "Full-time",
    pay: "$15–20/hr",
    description: "Assist licensed electricians with commercial electrical installations. Great entry point into a high-demand skilled trade.",
    requirements: ["High school diploma or GED", "Basic math skills", "Ability to lift 50 lbs", "Interest in electrical work"],
    fairChance: true,
    fairChanceNote: "Rosendin has a history of supporting second-chance employment and workforce reentry.",
    applyUrl: "https://www.rosendin.com/careers"
  },
  {
    id: 11,
    title: "Environmental Services (Housekeeping)",
    company: "Banner Health",
    location: "Phoenix, AZ",
    category: "healthcare",
    type: "Full-time",
    pay: "$14–17/hr",
    description: "Maintain cleanliness and sanitation in hospital and clinic environments. Important role supporting patient care with benefits included.",
    requirements: ["No experience required", "Attention to detail", "Ability to follow safety protocols", "Must pass background check (reviewed individually)"],
    fairChance: true,
    fairChanceNote: "Banner Health reviews criminal records on an individual basis and does not automatically disqualify applicants.",
    applyUrl: "https://www.bannerhealth.com/careers"
  },
  {
    id: 12,
    title: "Dietary Aide",
    company: "Abrazo Health",
    location: "Mesa, AZ",
    category: "healthcare",
    type: "Part-time / Full-time",
    pay: "$13–16/hr",
    description: "Prepare and deliver meals to patients, maintain kitchen cleanliness, and follow dietary guidelines. A great entry into the healthcare field.",
    requirements: ["No experience needed", "Food handler's card (can obtain after hire)", "Good communication skills", "Must be 18+"],
    fairChance: true,
    fairChanceNote: "Abrazo Health is part of Tenet Healthcare, which reviews applicants with criminal records individually.",
    applyUrl: "https://www.abrazohealth.com/careers"
  }
];
